function New-TierModelOu {
    <#
    .SYNOPSIS
    Apply OU creation plan by creating organizational units in Active Directory.
    
    .DESCRIPTION
    Executes OU creation actions from a plan generated by Get-TierModelOu.
    Creates OUs using New-ADOrganizationalUnit and applies optional inheritance
    settings (GPO inheritance blocking, security inheritance disabling).
    
    .PARAMETER Plan
    Plan object output from Get-TierModelOu containing Actions array.
    
    .PARAMETER DomainController
    Preferred domain controller for operations.
    
    .OUTPUTS
    PSCustomObject with Applied, Skipped, Errors, DurationMs, and Converged status.
    
    .EXAMPLE
    $config = Get-TierModelConfig
    $plan = Get-TierModelOu -Config $config -DomainController "DC01.contoso.com"
    $result = New-TierModelOu -Plan $plan -DomainController "DC01.contoso.com"
    
    .EXAMPLE
    $result = New-TierModelOu -Plan $plan -DomainController "DC01.contoso.com" -WhatIf
    #>
    [CmdletBinding(SupportsShouldProcess)]
    param(
        [Parameter(Mandatory)]
        [object]$Plan,
        
        [Parameter(Mandatory)]
        [string]$DomainController
    )
    
    $CorrelationId = $script:CorrelationId
    $startTime = Get-Date
    
    # Ensure we have a proper array for counting
    $createActions = @($Plan.Actions | Where-Object { $_.Action -eq 'CreateOU' })
    
    Write-TierModelLog -Level Info -Message "OuCreateStart" -Data @{
        CorrelationId = $CorrelationId
        DomainController = $DomainController
        WhatIf = $WhatIfPreference
        PlanActionCount = $createActions.Count
    } | Out-Null
    
    $applied = @()
    $skipped = @()
    $errors = @()
    
    try {
        if ($createActions.Count -eq 0) {
            Write-TierModelLog -Level Info -Message "No OU creation actions in plan" -Data @{
                CorrelationId = $CorrelationId
            } | Out-Null
        }
        
        foreach ($action in $createActions) {
            try {
                $ouData = $action.Data
                $ouName = $ouData.name
                $ouPath = $action.Path
                
                # Get description safely - use comment if description doesn't exist
                $ouDescription = if ($ouData.PSObject.Properties.Name -contains 'description') { 
                    $ouData.description 
                } elseif ($ouData.PSObject.Properties.Name -contains 'comment') { 
                    $ouData.comment 
                } else { 
                    $null 
                }
                
                Write-TierModelLog -Level Info -Message "OuCreateStart" -Data @{
                    Name = $ouName
                    Path = $ouPath
                    Description = $ouDescription
                    WhatIf = $WhatIfPreference
                    CorrelationId = $CorrelationId
                } | Out-Null
                
                if ($PSCmdlet.ShouldProcess("OU: $ouName", "Create organizational unit at $ouPath")) {
                    # Show creation progress
                    Write-Host "  ✅ Creating OU: $ouName" -ForegroundColor Green
                    
                    # Actual creation
                    $newOuParams = @{
                        Name = $ouName
                            Path = $ouPath
                            Server = $DomainController
                            Confirm = $false
                        }
                        
                        # Add optional properties if they exist
                        if ($ouDescription) {
                            $newOuParams['Description'] = $ouDescription
                        }
                        if ($ouData.PSObject.Properties.Name -contains 'protectFromAccidentalDeletion' -and $null -ne $ouData.protectFromAccidentalDeletion) {
                            $newOuParams['ProtectedFromAccidentalDeletion'] = $ouData.protectFromAccidentalDeletion
                        }
                        
                        $newOU = New-ADOrganizationalUnit @newOuParams -PassThru
                        
                        $actionsPerformed = @('CreateOU')
                        $warnings = @()
                        
                        # Configure GPO inheritance blocking if specified
                        if ($ouData.PSObject.Properties.Name -contains 'blockGpoInheritance' -and $ouData.blockGpoInheritance -eq $true) {
                            try {
                                Write-TierModelLog -Level Info -Message "OuBlockGpoStart" -Data @{
                                    OUName = $ouName
                                    DistinguishedName = $newOU.DistinguishedName
                                    CorrelationId = $CorrelationId
                                } | Out-Null
                                
                                Set-GPInheritance -Target $newOU.DistinguishedName -IsBlocked Yes -Server $DomainController | Out-Null
                                $actionsPerformed += 'BlockGpoInheritance'
                                
                                Write-TierModelLog -Level Info -Message "OuBlockGpoSuccess" -Data @{
                                    OUName = $ouName
                                    DistinguishedName = $newOU.DistinguishedName
                                    CorrelationId = $CorrelationId
                                } | Out-Null
                            } catch {
                                $warnings += "Failed to block GPO inheritance: $($_.Exception.Message)"
                                Write-TierModelLog -Level Warning -Message "OuBlockGpoWarning" -Data @{
                                    OUName = $ouName
                                    Error = $_.Exception.Message
                                    CorrelationId = $CorrelationId
                                } | Out-Null
                            }
                        }
                        
                        # Configure security inheritance blocking if specified
                        if ($ouData.PSObject.Properties.Name -contains 'disableInheritance' -and $ouData.disableInheritance -eq $true) {
                            try {
                                Write-TierModelLog -Level Info -Message "OuDisableSecInheritStart" -Data @{
                                    OUName = $ouName
                                    DistinguishedName = $newOU.DistinguishedName
                                    CorrelationId = $CorrelationId
                                } | Out-Null
                                
                                # Get the current ACL and disable inheritance
                                $acl = Get-Acl -Path "AD:\$($newOU.DistinguishedName)"
                                $acl.SetAccessRuleProtection($true, $true)  # Block inheritance, preserve existing permissions
                                Set-Acl -Path "AD:\$($newOU.DistinguishedName)" -AclObject $acl | Out-Null
                                $actionsPerformed += 'DisableSecurityInheritance'
                                
                                Write-TierModelLog -Level Info -Message "OuDisableSecInheritSuccess" -Data @{
                                    OUName = $ouName
                                    DistinguishedName = $newOU.DistinguishedName
                                    CorrelationId = $CorrelationId
                                } | Out-Null
                            } catch {
                                $warnings += "Failed to disable security inheritance: $($_.Exception.Message)"
                                Write-TierModelLog -Level Warning -Message "OuDisableSecInheritWarning" -Data @{
                                    OUName = $ouName
                                    Error = $_.Exception.Message
                                    CorrelationId = $CorrelationId
                                } | Out-Null
                            }
                        }
                        
                        $applied += [PSCustomObject]@{
                            Name = $ouName
                            DistinguishedName = $newOU.DistinguishedName
                            ObjectGUID = $newOU.ObjectGUID
                            ActionsPerformed = $actionsPerformed
                            Warnings = $warnings
                        }
                        
                        Write-TierModelLog -Level Info -Message "OuCreateSuccess" -Data @{
                            Name = $ouName
                            DistinguishedName = $newOU.DistinguishedName
                            ObjectGuid = $newOU.ObjectGUID
                            ActionsPerformed = $actionsPerformed
                            CorrelationId = $CorrelationId
                        } | Out-Null
                } else {
                    # ShouldProcess returned false - either WhatIf or user declined
                    $reason = if ($WhatIfPreference) { 'WhatIf' } else { 'UserDeclined' }
                    $skipped += [PSCustomObject]@{
                        Name = $ouName
                        Path = $ouPath
                        Reason = $reason
                        ActionsPlanned = @('CreateOU')
                    }
                }
            } catch {
                $errorMsg = "Failed to create OU '$($action.Name)': $($_.Exception.Message)"
                $errors += @{
                    Timestamp = Get-Date
                    Category = 'Execution'
                    Code = 'CreateOuFailed'
                    Message = $errorMsg
                    Context = @{
                        Name = $action.Name
                        Path = $action.Path
                        Exception = $_.Exception.Message
                    }
                }
                
                Write-TierModelLog -Level Error -Message "OuCreateError" -Data @{
                    Name = $action.Name
                    Path = $action.Path
                    ExceptionMessage = $_.Exception.Message
                    CorrelationId = $CorrelationId
                } | Out-Null
            }
        }
        
        $endTime = Get-Date
        $durationMs = [int]($endTime - $startTime).TotalMilliseconds
        $converged = $applied.Count -eq 0
        
        Write-TierModelLog -Level Info -Message "OuCreateComplete" -Data @{
            AppliedCount = $applied.Count
            SkippedCount = $skipped.Count
            ErrorCount = $errors.Count
            DurationMs = $durationMs
            Converged = $converged
            CorrelationId = $CorrelationId
        } | Out-Null
        
        return [PSCustomObject]@{
            Applied = $applied
            Skipped = $skipped
            Errors = $errors
            DurationMs = $durationMs
            Converged = $converged
            CorrelationId = $CorrelationId
        }
        
    } catch {
        $endTime = Get-Date
        $durationMs = [int]($endTime - $startTime).TotalMilliseconds
        
        $errors += @{
            Timestamp = Get-Date
            Category = 'Execution'
            Code = 'OuApplyFailed'
            Message = "OU application failed: $($_.Exception.Message)"
            Context = @{
                Exception = $_.Exception.Message
            }
        }
        
        Write-TierModelLog -Level Error -Message "OU application failed" -Data @{
            Exception = $_.Exception.Message
            DurationMs = $durationMs
            CorrelationId = $CorrelationId
        } | Out-Null
        
        return [PSCustomObject]@{
            Applied = $applied
            Skipped = $skipped
            Errors = $errors
            DurationMs = $durationMs
            Converged = $false
            CorrelationId = $CorrelationId
        }
    }
}