function New-TierModelOu {
    <#
    .SYNOPSIS
    Apply OU creation plan by creating organizational units in Active Directory,
    using a three-phase flow that eliminates non-canonical DACL failures.

    .DESCRIPTION
    Executes OU creation actions from a plan generated by Get-TierModelOu using a
    phased approach that prevents the InvalidOperationException thrown by AD's
    AddAccessRule when a parent OU has a non-canonical DACL:

      Phase 1 — Create all OUs top-down WITHOUT ProtectedFromAccidentalDeletion and
                 WITHOUT ACL config. After each create, verify canonical and auto-
                 remediate if needed (silent). Then apply PFAD to all configured OUs
                 and re-verify canonical.
      Phase 2 — Disable security inheritance per OU (top-down) via DC-pinned
                 S.DS.P reads+writes with canonical sort applied atomically.
                 Verifies DiscretionaryAclProtected ControlFlags bit with retry/backoff.
      Phase 3 — Block GPO inheritance per OU via Set-GPInheritance.
                 Verifies GpoInheritanceBlocked with retry/backoff.
                 No canonical check needed (gPOptions only, not ntSecurityDescriptor).

    All ACL reads and writes are DC-pinned to -PreferredDc (no AD: provider usage).
    Canonical remediation is silent (Verbose/Debug only) and does NOT count as an
    error. Hard errors halt the phase and include delete-and-rerun guidance.

    .PARAMETER Plan
    Plan object output from Get-TierModelOu containing Actions array.

    .PARAMETER PreferredDc
    FQDN or hostname of the domain controller to pin all operations to.
    Alias: DomainController (for backwards compatibility with callers).

    .OUTPUTS
    PSCustomObject @{
        Applied             = PSCustomObject[] per OU (Name, DistinguishedName, ObjectGUID, ActionsPerformed, Warnings)
        Skipped             = PSCustomObject[] per OU
        Errors              = hashtable[]  (Timestamp, Category, Code, Message, Context)
        DurationMs          = int
        Converged           = bool
        CorrelationId       = string
        CanonicalRemediations = int   # count of successful inline remediations (observability only)
    }

    .EXAMPLE
    $config = Get-TierModelConfig
    $plan = Get-TierModelOu -Config $config -DomainController "DC01.contoso.com"
    $result = New-TierModelOu -Plan $plan -PreferredDc "DC01.contoso.com"

    .EXAMPLE
    $result = New-TierModelOu -Plan $plan -DomainController "DC01.contoso.com" -WhatIf
    #>
    [CmdletBinding(SupportsShouldProcess)]
    param(
        [Parameter(Mandatory)]
        [object]$Plan,

        [Parameter(Mandatory)]
        [Alias('DomainController')]
        [string]$PreferredDc
    )
    
    $CorrelationId = $script:CorrelationId
    $startTime     = Get-Date

    $createActions = @($Plan.Actions | Where-Object { $_.Action -eq 'CreateOU' })

    Write-TierModelLog -Level Info -Message "OuCreateStart" -Data @{
        CorrelationId    = $CorrelationId
        PreferredDc      = $PreferredDc
        WhatIf           = $WhatIfPreference
        PlanActionCount  = $createActions.Count
    } | Out-Null

    $applied              = [System.Collections.Generic.List[object]]::new()
    $skipped              = [System.Collections.Generic.List[object]]::new()
    $errors               = [System.Collections.Generic.List[object]]::new()
    $canonicalRemediations = 0
    $maxRemediationAttempts = 2

    # -----------------------------------------------------------------------
    # Internal helper: post-write canonical verify + auto-remediate (silent).
    # Returns $true if canonical confirmed; $false if persistently non-canonical.
    # On persistent failure, adds a hard error entry and sets $script:phaseAbort.
    # -----------------------------------------------------------------------
    function Invoke-CanonicalVerifyAndRemediate {
        param([string]$Dn, [string]$Dc, [string]$OuName)

        for ($attempt = 1; $attempt -le $maxRemediationAttempts; $attempt++) {
            $check = Test-TierModelCanonicalAcl -PreferredDc $Dc -DistinguishedName $Dn
            if ($check.IsCanonical) { return $true }

            Write-Debug "Repair-TierModelCanonicalAcl: '$Dn' non-canonical (attempt $attempt/$maxRemediationAttempts) — repairing silently."
            try {
                $null = Repair-TierModelCanonicalAcl -PreferredDc $Dc -DistinguishedName $Dn
                # Increment the outer function's counter (Scope 1 = one level up from this nested function)
                Set-Variable -Name canonicalRemediations -Value ($canonicalRemediations + 1) -Scope 1
            } catch {
                # Repair threw (e.g. AceCountMismatch) — fall through to hard-error below.
                Write-Debug "Repair-TierModelCanonicalAcl threw on '$Dn': $($_.Exception.Message)"
            }
        }

        # Final re-check after last remediation attempt
        $finalCheck = Test-TierModelCanonicalAcl -PreferredDc $Dc -DistinguishedName $Dn
        if ($finalCheck.IsCanonical) { return $true }

        return $false
    }

    # -----------------------------------------------------------------------
    # WhatIf shortcut — report planned actions, return empty result
    # -----------------------------------------------------------------------
    if ($WhatIfPreference) {
        foreach ($action in $createActions) {
            $skipped.Add([PSCustomObject]@{
                Name           = $action.Data.name
                Path           = $action.Path
                Reason         = 'WhatIf'
                ActionsPlanned = @('CreateOU')
            })
        }
        $durationMs = [int]((Get-Date) - $startTime).TotalMilliseconds
        return [PSCustomObject]@{
            Applied               = @()                  # none applied in WhatIf mode
            Skipped               = $skipped.ToArray()
            Errors                = @()
            DurationMs            = $durationMs
            Converged             = $true
            CorrelationId         = $CorrelationId
            CanonicalRemediations = 0
        }
    }

    try {
        Add-Type -AssemblyName System.DirectoryServices.Protocols

        # ===================================================================
        # PHASE 1 — Create all OUs top-down (NO PFAD, NO ACL config)
        # ===================================================================
        Write-TierModelLog -Level Info -Message "OuPhase1Start" -Data @{
            CorrelationId = $CorrelationId; ActionCount = $createActions.Count
        } | Out-Null

        $createdSoFar = [System.Collections.Generic.List[string]]::new()   # DNs created this run

        foreach ($action in $createActions) {
            $ouData        = $action.Data
            $ouName        = $ouData.name
            $ouPath        = $action.Path
            $ouDescription = if ($ouData.PSObject.Properties.Name -contains 'description') {
                $ouData.description
            } elseif ($ouData.PSObject.Properties.Name -contains 'comment') {
                $ouData.comment
            } else { $null }

            if (-not $PSCmdlet.ShouldProcess("OU: $ouName", "Create organizational unit at $ouPath")) {
                $skipped.Add([PSCustomObject]@{
                    Name           = $ouName
                    Path           = $ouPath
                    Reason         = 'UserDeclined'
                    ActionsPlanned = @('CreateOU')
                })
                continue
            }

            Write-Host "  `u{2705} Creating OU: $ouName" -ForegroundColor Green

            $newOU = $null
            try {
                $newOuParams = @{
                    Name    = $ouName
                    Path    = $ouPath
                    Server  = $PreferredDc
                    Confirm = $false
                    PassThru = $true
                }
                if ($ouDescription) { $newOuParams['Description'] = $ouDescription }
                # NOTE: ProtectedFromAccidentalDeletion intentionally omitted here — applied in Phase 1 final step.

                $newOU = New-ADOrganizationalUnit @newOuParams
                $createdSoFar.Add($newOU.DistinguishedName)

                Write-TierModelLog -Level Info -Message "OuCreateSuccess" -Data @{
                    Name = $ouName; DistinguishedName = $newOU.DistinguishedName
                    CorrelationId = $CorrelationId
                } | Out-Null
            } catch {
                $errMsg = "Failed to create OU '$ouName': $($_.Exception.Message)"
                $errors.Add(@{
                    Timestamp = Get-Date; Category = 'Execution'; Code = 'CreateOuFailed'
                    Message   = $errMsg
                    Context   = @{ Name = $ouName; Path = $ouPath; Exception = $_.Exception.Message
                                   CreatedSoFar = $createdSoFar.ToArray() }
                })
                Write-Host "  `u{274C} $errMsg" -ForegroundColor Red
                if ($createdSoFar.Count -gt 0) {
                    Write-Host "  Delete the following OUs and re-run the deployment:" -ForegroundColor Yellow
                    foreach ($dn in $createdSoFar) { Write-Host "    - $dn" -ForegroundColor Yellow }
                    Write-Host "  Do NOT modify these OUs manually. Delete and re-run." -ForegroundColor Yellow
                }
                Write-TierModelLog -Level Error -Message "OuCreateError" -Data @{
                    Name = $ouName; Path = $ouPath
                    ExceptionMessage = $_.Exception.Message; CorrelationId = $CorrelationId
                } | Out-Null
                # Hard-stop Phase 1 on create failure.
                throw "Phase1Abort:$ouName"
            }

            # Post-create canonical verify + silent remediation
            if (-not (Invoke-CanonicalVerifyAndRemediate -Dn $newOU.DistinguishedName -Dc $PreferredDc -OuName $ouName)) {
                $errMsg = "OU '$ouName' ($($newOU.DistinguishedName)) could not be made canonical after $maxRemediationAttempts remediation attempt(s)."
                $errors.Add(@{
                    Timestamp = Get-Date; Category = 'Execution'; Code = 'CanonicalRemediationFailed'
                    Message   = $errMsg
                    Context   = @{ Name = $ouName; DistinguishedName = $newOU.DistinguishedName
                                   CreatedSoFar = $createdSoFar.ToArray() }
                })
                Write-Host "  `u{274C} $errMsg" -ForegroundColor Red
                Write-Host "  Delete the following OUs and re-run the deployment:" -ForegroundColor Yellow
                foreach ($dn in $createdSoFar) { Write-Host "    - $dn" -ForegroundColor Yellow }
                Write-Host "  Do NOT modify these OUs manually. Delete and re-run." -ForegroundColor Yellow
                throw "Phase1Abort:CanonicalRemediationFailed:$ouName"
            }

            $applied.Add([PSCustomObject]@{
                Name              = $ouName
                DistinguishedName = $newOU.DistinguishedName
                ObjectGUID        = $newOU.ObjectGUID
                ActionsPerformed  = [System.Collections.Generic.List[string]]@('CreateOU')
                Warnings          = @()
            })
        }

        # -------------------------------------------------------------------
        # Phase 1 final step — apply ProtectedFromAccidentalDeletion top-down
        # -------------------------------------------------------------------
        $pfadActions = @($createActions | Where-Object {
            $_.Data.PSObject.Properties.Name -contains 'protectFromAccidentalDeletion' -and
            $_.Data.protectFromAccidentalDeletion -eq $true
        })

        foreach ($action in $pfadActions) {
            $ouName = $action.Data.name
            # Find the applied entry so we have the real DN from AD
            $appliedEntry = $applied | Where-Object { $_.Name -eq $ouName } | Select-Object -First 1
            if (-not $appliedEntry) { continue }   # was skipped earlier

            $dn = $appliedEntry.DistinguishedName
            try {
                Set-ADOrganizationalUnit -Identity $dn -ProtectedFromAccidentalDeletion $true -Server $PreferredDc -Confirm:$false
            } catch {
                $errMsg = "Failed to apply ProtectedFromAccidentalDeletion to OU '$ouName' ($dn): $($_.Exception.Message)"
                $errors.Add(@{
                    Timestamp = Get-Date; Category = 'Execution'; Code = 'PfadApplyFailed'
                    Message   = $errMsg
                    Context   = @{ Name = $ouName; DistinguishedName = $dn; Exception = $_.Exception.Message }
                })
                Write-Host "  `u{274C} $errMsg" -ForegroundColor Red
                throw "Phase1Abort:PfadApplyFailed:$ouName"
            }

            # Post-PFAD canonical verify + remediation (PFAD writes an explicit Deny-delete ACE,
            # which can non-canonicalize when an inherited Deny is already present above this OU)
            if (-not (Invoke-CanonicalVerifyAndRemediate -Dn $dn -Dc $PreferredDc -OuName $ouName)) {
                $errMsg = "OU '$ouName' ($dn) non-canonical after PFAD apply, remediation failed after $maxRemediationAttempts attempt(s)."
                $errors.Add(@{
                    Timestamp = Get-Date; Category = 'Execution'; Code = 'CanonicalRemediationFailed'
                    Message   = $errMsg
                    Context   = @{ Name = $ouName; DistinguishedName = $dn }
                })
                Write-Host "  `u{274C} $errMsg" -ForegroundColor Red
                throw "Phase1Abort:CanonicalRemediationFailed:PFAD:$ouName"
            }

            $appliedEntry.ActionsPerformed.Add('ProtectedFromAccidentalDeletion')
            Write-TierModelLog -Level Info -Message "OuPfadApplied" -Data @{
                Name = $ouName; DistinguishedName = $dn; CorrelationId = $CorrelationId
            } | Out-Null
        }

        Write-TierModelLog -Level Info -Message "OuPhase1Complete" -Data @{
            CorrelationId = $CorrelationId; AppliedCount = $applied.Count
        } | Out-Null

        # ===================================================================
        # PHASE 2 — Disable security inheritance (top-down, DC-pinned S.DS.P)
        # ===================================================================
        $inheritanceActions = @($createActions | Where-Object {
            $_.Data.PSObject.Properties.Name -contains 'disableInheritance' -and
            $_.Data.disableInheritance -eq $true
        })

        foreach ($action in $inheritanceActions) {
            $ouName       = $action.Data.name
            $appliedEntry = $applied | Where-Object { $_.Name -eq $ouName } | Select-Object -First 1
            if (-not $appliedEntry) { continue }
            $dn = $appliedEntry.DistinguishedName

            Write-TierModelLog -Level Info -Message "OuDisableSecInheritStart" -Data @{
                OUName = $ouName; DistinguishedName = $dn; CorrelationId = $CorrelationId
            } | Out-Null

            # DC-pinned read of current SD bytes
            $id2   = New-Object System.DirectoryServices.Protocols.LdapDirectoryIdentifier($PreferredDc)
            $conn2 = New-Object System.DirectoryServices.Protocols.LdapConnection($id2)
            $conn2.SessionOptions.Signing = $true
            $conn2.SessionOptions.Sealing = $true
            $conn2.Bind()

            $ctl2 = New-Object System.DirectoryServices.Protocols.SecurityDescriptorFlagControl(
                [System.DirectoryServices.Protocols.SecurityMasks]::Dacl)
            $req2 = New-Object System.DirectoryServices.Protocols.SearchRequest(
                $dn, '(objectClass=*)', 'Base', [string[]]@('ntSecurityDescriptor'))
            [void]$req2.Controls.Add($ctl2)
            $sdBytes2 = ($conn2.SendRequest($req2)).Entries[0].Attributes['ntSecurityDescriptor'].GetValues([byte[]])[0]

            # Parse, call SetAccessRuleProtection($true,$true), then canonical-sort in one op.
            # We work on the RawSecurityDescriptor to build the new binary form.
            $csd2     = New-Object System.Security.AccessControl.CommonSecurityDescriptor($true, $true, $sdBytes2, 0)
            $dacl2    = $csd2.DiscretionaryAcl

            # Apply protection (copy-inherited → all ACEs become explicit; inherited flag cleared)
            $csd2.SetDiscretionaryAclProtection($true, $true)   # copyInherited=$true
            $dacl2 = $csd2.DiscretionaryAcl

            # Build sort keys on the post-protection ACEs (original index = position after protection)
            $aceList2 = [System.Collections.Generic.List[object]]::new()
            $idx2 = 0
            foreach ($a in $dacl2) {
                $q2 = $a -as [System.Security.AccessControl.QualifiedAce]
                $isInherited2 = $null -ne $q2 -and ((([int]$a.AceFlags) -band ([int][System.Security.AccessControl.AceFlags]::Inherited)) -ne 0)
                $isDeny2      = $null -ne $q2 -and $q2.AceQualifier -eq [System.Security.AccessControl.AceQualifier]::AccessDenied
                $rank2 = if (-not $isInherited2 -and $isDeny2)      { 0 }
                         elseif (-not $isInherited2 -and -not $isDeny2) { 1 }
                         elseif ($isInherited2 -and $isDeny2)        { 2 }
                         else                                        { 3 }
                $isObj2 = ($a -is [System.Security.AccessControl.ObjectAce]) ? 1 : 0
                $aceList2.Add([PSCustomObject]@{ Ace = $a; SortKey = ($rank2 * 10000 + $isObj2 * 1000 + $idx2) })
                $idx2++
            }
            $sorted2 = $aceList2 | Sort-Object -Property SortKey -Stable

            # SetAccessRuleProtection is conveyed via the Control flags in the SD header.
            # We need the new (protected) SD, so re-derive it from csd2.
            $protectedBytes = New-Object byte[] $csd2.BinaryLength
            $csd2.GetBinaryForm($protectedBytes, 0)
            $rawSd2p = New-Object System.Security.AccessControl.RawSecurityDescriptor($protectedBytes, 0)
            $newDacl2p = New-Object System.Security.AccessControl.RawAcl($rawSd2p.DiscretionaryAcl.Revision, $sorted2.Count)
            foreach ($entry2 in $sorted2) { $newDacl2p.InsertAce($newDacl2p.Count, $entry2.Ace) }
            $rawSd2p.DiscretionaryAcl = $newDacl2p

            $finalBytes2 = New-Object byte[] $rawSd2p.BinaryLength
            $rawSd2p.GetBinaryForm($finalBytes2, 0)

            # DC-pinned write via ModifyRequest (same connection)
            $mod2 = New-Object System.DirectoryServices.Protocols.ModifyRequest
            $mod2.DistinguishedName = $dn
            $dam2 = New-Object System.DirectoryServices.Protocols.DirectoryAttributeModification
            $dam2.Name = 'ntSecurityDescriptor'
            $dam2.Operation = [System.DirectoryServices.Protocols.DirectoryAttributeOperation]::Replace
            [void]$dam2.Add($finalBytes2)
            [void]$mod2.Modifications.Add($dam2)
            $sdCtl2 = New-Object System.DirectoryServices.Protocols.SecurityDescriptorFlagControl(
                [System.DirectoryServices.Protocols.SecurityMasks]::Dacl)
            [void]$mod2.Controls.Add($sdCtl2)
            [void]$conn2.SendRequest($mod2)

            # Post-write canonical verify + remediation
            if (-not (Invoke-CanonicalVerifyAndRemediate -Dn $dn -Dc $PreferredDc -OuName $ouName)) {
                $errMsg = "OU '$ouName' ($dn) non-canonical after disable-inheritance write, remediation failed."
                $errors.Add(@{
                    Timestamp = Get-Date; Category = 'Execution'; Code = 'DisableSecurityInheritanceUnverified'
                    Message   = $errMsg
                    Context   = @{ Name = $ouName; DistinguishedName = $dn }
                })
                Write-Host "  `u{274C} $errMsg" -ForegroundColor Red
                continue
            }

            # Verify DiscretionaryAclProtected ControlFlags bit via DC-pinned readback with retry/backoff
            $secVerified = $false
            $secAttempts = 0
            $secLastErr  = $null
            $secMaxAttempts = 4
            while (-not $secVerified -and $secAttempts -lt $secMaxAttempts) {
                $secAttempts++
                try {
                    $ctl3 = New-Object System.DirectoryServices.Protocols.SecurityDescriptorFlagControl(
                        [System.DirectoryServices.Protocols.SecurityMasks]::Dacl)
                    $req3 = New-Object System.DirectoryServices.Protocols.SearchRequest(
                        $dn, '(objectClass=*)', 'Base', [string[]]@('ntSecurityDescriptor'))
                    [void]$req3.Controls.Add($ctl3)
                    $rbBytes = ($conn2.SendRequest($req3)).Entries[0].Attributes['ntSecurityDescriptor'].GetValues([byte[]])[0]
                    $rbCsd   = New-Object System.Security.AccessControl.CommonSecurityDescriptor($true, $true, $rbBytes, 0)
                    $rbProtected = (($rbCsd.ControlFlags -band [System.Security.AccessControl.ControlFlags]::DiscretionaryAclProtected) -ne 0)
                    if ($rbCsd.DiscretionaryAcl.IsCanonical -and $rbProtected) {
                        $secVerified = $true; break
                    }
                } catch { $secLastErr = $_.Exception.Message }
                if (-not $secVerified -and $secAttempts -lt $secMaxAttempts) {
                    Start-Sleep -Milliseconds ([int](500 * [Math]::Pow(2, $secAttempts - 1)))
                }
            }

            if ($secVerified) {
                $appliedEntry.ActionsPerformed.Add('DisableSecurityInheritance')
                Write-TierModelLog -Level Info -Message "OuDisableSecInheritSuccess" -Data @{
                    OUName = $ouName; DistinguishedName = $dn
                    Attempts = $secAttempts; CorrelationId = $CorrelationId
                } | Out-Null
            } else {
                $errMsg = "Security inheritance was not disabled for OU '$ouName' (after $secAttempts attempts). $secLastErr"
                $errors.Add(@{
                    Timestamp = Get-Date; Category = 'Execution'; Code = 'DisableSecurityInheritanceUnverified'
                    Message   = $errMsg
                    Context   = @{ Name = $ouName; DistinguishedName = $dn; Attempts = $secAttempts }
                })
                Write-Host "  `u{274C} $errMsg" -ForegroundColor Red
                Write-Host "  Delete OU '$ouName' ($dn) and re-run to recreate it cleanly." -ForegroundColor Yellow
                Write-TierModelLog -Level Error -Message "OuDisableSecInheritUnverified" -Data @{
                    OUName = $ouName; DistinguishedName = $dn; Attempts = $secAttempts
                    Error = $secLastErr; CorrelationId = $CorrelationId
                } | Out-Null
            }
        }

        Write-TierModelLog -Level Info -Message "OuPhase2Complete" -Data @{ CorrelationId = $CorrelationId } | Out-Null

        # ===================================================================
        # PHASE 3 — Block GPO inheritance (top-down, verify only)
        # gPOptions only — no ntSecurityDescriptor mutation, no canonical check needed.
        # ===================================================================
        $gpoActions = @($createActions | Where-Object {
            $_.Data.PSObject.Properties.Name -contains 'blockGpoInheritance' -and
            $_.Data.blockGpoInheritance -eq $true
        })

        foreach ($action in $gpoActions) {
            $ouName       = $action.Data.name
            $appliedEntry = $applied | Where-Object { $_.Name -eq $ouName } | Select-Object -First 1
            if (-not $appliedEntry) { continue }
            $dn = $appliedEntry.DistinguishedName

            Write-TierModelLog -Level Info -Message "OuBlockGpoStart" -Data @{
                OUName = $ouName; DistinguishedName = $dn; CorrelationId = $CorrelationId
            } | Out-Null

            $gpoVerified = $false
            $gpoAttempts = 0
            $gpoLastErr  = $null
            $gpoMax      = 4
            while (-not $gpoVerified -and $gpoAttempts -lt $gpoMax) {
                $gpoAttempts++
                try {
                    Set-GPInheritance -Target $dn -IsBlocked Yes -Server $PreferredDc -ErrorAction Stop | Out-Null
                } catch { $gpoLastErr = $_.Exception.Message }
                try {
                    $gpoState = Get-GPInheritance -Target $dn -Server $PreferredDc -ErrorAction Stop
                    if ($gpoState.GpoInheritanceBlocked -eq $true) { $gpoVerified = $true; break }
                } catch { $gpoLastErr = $_.Exception.Message }
                if (-not $gpoVerified -and $gpoAttempts -lt $gpoMax) {
                    Start-Sleep -Milliseconds ([int](500 * [Math]::Pow(2, $gpoAttempts - 1)))
                }
            }

            if ($gpoVerified) {
                $appliedEntry.ActionsPerformed.Add('BlockGpoInheritance')
                Write-TierModelLog -Level Info -Message "OuBlockGpoSuccess" -Data @{
                    OUName = $ouName; DistinguishedName = $dn
                    Attempts = $gpoAttempts; CorrelationId = $CorrelationId
                } | Out-Null
            } else {
                $errMsg = "Block GPO Inheritance flag was not set for OU '$ouName' (after $gpoAttempts attempts). $gpoLastErr"
                $errors.Add(@{
                    Timestamp = Get-Date; Category = 'Execution'; Code = 'BlockGpoInheritanceUnverified'
                    Message   = $errMsg
                    Context   = @{ Name = $ouName; DistinguishedName = $dn; Attempts = $gpoAttempts }
                })
                Write-Host "  `u{274C} $errMsg" -ForegroundColor Red
                Write-Host "  Delete OU '$ouName' ($dn) and re-run to recreate it cleanly." -ForegroundColor Yellow
                Write-TierModelLog -Level Error -Message "OuBlockGpoUnverified" -Data @{
                    OUName = $ouName; DistinguishedName = $dn; Attempts = $gpoAttempts
                    Error = $gpoLastErr; CorrelationId = $CorrelationId
                } | Out-Null
            }
        }

        $durationMs = [int]((Get-Date) - $startTime).TotalMilliseconds
        $converged  = $applied.Count -eq 0 -and $errors.Count -eq 0

        Write-TierModelLog -Level Info -Message "OuCreateComplete" -Data @{
            AppliedCount          = $applied.Count
            SkippedCount          = $skipped.Count
            ErrorCount            = $errors.Count
            CanonicalRemediations = $canonicalRemediations
            DurationMs            = $durationMs
            Converged             = $converged
            CorrelationId         = $CorrelationId
        } | Out-Null

        # Convert List<> entries so ActionsPerformed is a plain array in the output
        $appliedOut = $applied | ForEach-Object {
            [PSCustomObject]@{
                Name              = $_.Name
                DistinguishedName = $_.DistinguishedName
                ObjectGUID        = $_.ObjectGUID
                ActionsPerformed  = $_.ActionsPerformed.ToArray()
                Warnings          = $_.Warnings
            }
        }

        return [PSCustomObject]@{
            Applied               = @($appliedOut)
            Skipped               = $skipped.ToArray()
            Errors                = $errors.ToArray()
            DurationMs            = $durationMs
            Converged             = $converged
            CorrelationId         = $CorrelationId
            CanonicalRemediations = $canonicalRemediations
        }

    } catch {
        # Catch Phase1Abort signals and any unexpected exceptions
        $durationMs = [int]((Get-Date) - $startTime).TotalMilliseconds

        # Only add a generic error if this was not already an intentional Phase1Abort
        # (Phase1Abort already pushed a structured error entry before throwing)
        $abortMsg = $_.Exception.Message
        if ($abortMsg -notlike 'Phase1Abort:*') {
            $errors.Add(@{
                Timestamp = Get-Date; Category = 'Execution'; Code = 'OuApplyFailed'
                Message   = "OU application failed: $abortMsg"
                Context   = @{ Exception = $abortMsg }
            })
            Write-TierModelLog -Level Error -Message "OuApplyFailed" -Data @{
                Exception = $abortMsg; DurationMs = $durationMs; CorrelationId = $CorrelationId
            } | Out-Null
        }

        $appliedOut = $applied | ForEach-Object {
            [PSCustomObject]@{
                Name              = $_.Name
                DistinguishedName = $_.DistinguishedName
                ObjectGUID        = $_.ObjectGUID
                ActionsPerformed  = $_.ActionsPerformed.ToArray()
                Warnings          = $_.Warnings
            }
        }

        return [PSCustomObject]@{
            Applied               = @($appliedOut)
            Skipped               = $skipped.ToArray()
            Errors                = $errors.ToArray()
            DurationMs            = $durationMs
            Converged             = $false
            CorrelationId         = $CorrelationId
            CanonicalRemediations = $canonicalRemediations
        }
    }
}